nohup python3 train_and_countCells.py -a 0 --dest countCells_autogen_sixthrun > sixthrun_1.txt
nohup python3 train_and_countCells.py -a 1 --dest countCells_autogen_sixthrun > sixthrun_1.txt
nohup python3 train_and_countCells.py -a 2 --dest countCells_autogen_sixthrun > sixthrun_2.txt
nohup python3 train_and_countCells.py -a 3 --dest countCells_autogen_sixthrun > sixthrun_3.txt
nohup python3 train_and_countCells.py -a 4 --dest countCells_autogen_sixthrun > sixthrun_4.txt
nohup python3 train_and_countCells.py -a 5 --dest countCells_autogen_sixthrun > sixthrun_5.txt
nohup python3 train_and_countCells.py -a 6 --dest countCells_autogen_sixthrun > sixthrun_6.txt
nohup python3 train_and_countCells.py -a 7 --dest countCells_autogen_sixthrun > sixthrun_7.txt
nohup python3 train_and_countCells.py -a 8 --dest countCells_autogen_sixthrun > sixthrun_8.txt
nohup python3 train_and_countCells.py -a 9 --dest countCells_autogen_sixthrun > sixthrun_9.txt
nohup python3 train_and_countCells.py -a 10 --dest countCells_autogen_sixthrun > sixthrun_10.txt
nohup python3 train_and_countCells.py -a 11 --dest countCells_autogen_sixthrun > sixthrun_11.txt
nohup python3 train_and_countCells.py -a 12 --dest countCells_autogen_sixthrun > sixthrun_12.txt
